//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAReportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comentario
    {
        public int ID_Comentario { get; set; }
        public Nullable<int> ID_Noticia { get; set; }
        public Nullable<int> ID_Usuario { get; set; }
        public string Contenido { get; set; }
        public Nullable<System.DateTime> Fecha_pub { get; set; }
    
        public virtual Noticia Noticia { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
