//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAReportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empresa()
        {
            this.Historial_Hoja_Vida = new HashSet<Historial_Hoja_Vida>();
        }
    
        public int ID_Empresa { get; set; }
        public Nullable<int> ID_Usuario { get; set; }
        public string RUC { get; set; }
        public string Correo { get; set; }
        public string Telefono { get; set; }
        public string Razon_social { get; set; }
        public string Empresa1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Historial_Hoja_Vida> Historial_Hoja_Vida { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
