//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAReportes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WEBEntities : DbContext
    {
        public WEBEntities()
            : base("name=WEBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alumno> Alumno { get; set; }
        public virtual DbSet<Archivo_Investigacion> Archivo_Investigacion { get; set; }
        public virtual DbSet<Clic> Clic { get; set; }
        public virtual DbSet<Comentario> Comentario { get; set; }
        public virtual DbSet<Curso> Curso { get; set; }
        public virtual DbSet<Descarga_ArchivoI> Descarga_ArchivoI { get; set; }
        public virtual DbSet<Det_Archivo_Inv> Det_Archivo_Inv { get; set; }
        public virtual DbSet<Det_Certificado> Det_Certificado { get; set; }
        public virtual DbSet<Det_Exp_Laboral> Det_Exp_Laboral { get; set; }
        public virtual DbSet<Det_Form_Acad> Det_Form_Acad { get; set; }
        public virtual DbSet<Det_Partic_Proyecto> Det_Partic_Proyecto { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<Evento> Evento { get; set; }
        public virtual DbSet<Historial_Hoja_Vida> Historial_Hoja_Vida { get; set; }
        public virtual DbSet<Hoja_Vida> Hoja_Vida { get; set; }
        public virtual DbSet<Invitado> Invitado { get; set; }
        public virtual DbSet<Noticia> Noticia { get; set; }
        public virtual DbSet<Participantes> Participantes { get; set; }
        public virtual DbSet<Profesor> Profesor { get; set; }
        public virtual DbSet<Proyecto> Proyecto { get; set; }
        public virtual DbSet<Proyecto_Constr> Proyecto_Constr { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
