//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumno
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alumno()
        {
            this.Hoja_Vida = new HashSet<Hoja_Vida>();
        }
    
        public int ID_Alumno { get; set; }
        public Nullable<int> ID_Usuario { get; set; }
        public Nullable<int> ID_Usuario_crea { get; set; }
        public Nullable<int> ID_Usuario_mod { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Correo { get; set; }
        public string Celular { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> Ciclo { get; set; }
        public Nullable<int> DNI { get; set; }
        public Nullable<int> Estado { get; set; }
        public string Tipo { get; set; }
        public string Link_file_CV { get; set; }
        public string Testimonio { get; set; }
        public string Puesto_empresa { get; set; }
        public string Promocion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hoja_Vida> Hoja_Vida { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual Usuario Usuario2 { get; set; }
    }
}
