//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clic
    {
        public int ID_Clic { get; set; }
        public Nullable<int> ID_Usuario { get; set; }
        public Nullable<int> Cont_ArchivoI { get; set; }
        public Nullable<int> Cont_Noticias { get; set; }
        public Nullable<int> Cont_Eventos { get; set; }
        public Nullable<int> Cont_AcercaDe { get; set; }
        public Nullable<int> Cont_Proyectos { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
