//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Det_Form_Acad
    {
        public int ID_HojaVida { get; set; }
        public string Universidad { get; set; }
        public string Ciclo { get; set; }
        public string Colegio { get; set; }
    
        public virtual Hoja_Vida Hoja_Vida { get; set; }
    }
}
